### ISSUE TITLE
How to use dio_cookie_manager with dio_http?

### ISSUE THREAD

**Issue by maxim-gapeenko-idf** [dart-tools/dio_http#5]
Hey! How can I use dio_cookie_manager with dio_http?

dio_cookie_manager imports usual dio, is there any version with dio_http import?

**Comment by jgoyvaerts** [comment]
I still have to publish a version of dio_cookie_manager which imports dio_http to pub.dev, I'll try to get it done asap.
For now you can use a workaround by adding the package by git reference in your pubspec file. See this url for more info:
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

It should look something like this:
```
dependencies:
  dio_cookie_manager:
    git:
      url: https://github.com/dart-tools/dio_http.git
      path: plugins/cookie_manager
```
